### ISSUE TITLE
Exe doesn't run on my system

### ISSUE THREAD

**Issue by ABoss** [robertfoster550/Eternal_Draft_Simulator#1]
Hi Robert,
Thanks for your great project, I was able to run version 1.0 or 1.2 a couple weeks ago. But today I tried the newest version (1.41) and the exe fails to run ("Fatal error detected" but no helpful other description).
Maybe it is an easy recompile but otherwise no worries, I could still try to run the python files by themselves instead I suppose?
Thank you,
Arno

**Comment by robertfoster550** [comment]
Hi Arno,

Thank you for letting me know! I will look into that and see if I can
figure out why it didn't work this time. Hopefully I can fix it quickly.
I'll let you know.

Cheers,
Robert

**Comment by robertfoster550** [comment]
Hey!

I had a typo in one of the packages of this build, which I think was the trouble. So, I've got it sorted. I also added the new cards, so version 1.42 should work for you. I hope you enjoy! And feel free to let me know if you have any ideas of what you would like to see in future versions.

All the best,
Robert
